/** @type {import('tailwindcss').Config} */

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    container: {
      center: true,
    },
    extend: {
      colors: {
        background: "#0f131d",
        surface: "#0f131d",
        "surface-dim": "#0f131d",
        "surface-container-lowest": "#0a0e18",
        "surface-container-low": "#171b26",
        "surface-container": "#1c1f2a",
        "surface-container-high": "#262a35",
        "surface-container-highest": "#313540",
        "surface-bright": "#353944",
        primary: "#c3f5ff",
        "primary-container": "#00e5ff",
        "primary-fixed-dim": "#00daf3",
        secondary: "#ffd799",
        "secondary-container": "#feb300",
        tertiary: "#ffe8e4",
        "tertiary-container": "#ffc2ba",
        error: "#ffb4ab",
        "error-container": "#93000a",
        outline: "#849396",
        "outline-variant": "#3b494c",
        "on-background": "#dfe2f1",
        "on-surface": "#dfe2f1",
        "on-surface-variant": "#bac9cc",
        "on-primary": "#00363d",
        "on-primary-container": "#00626e",
        "on-secondary": "#432c00",
        "on-secondary-container": "#6a4800",
        "on-tertiary": "#690002",
        "on-tertiary-container": "#b30e0e",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['3.5rem', { lineHeight: '0.95', letterSpacing: '-0.05em', fontWeight: '800' }],
        'headline-md': ['1.75rem', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'body-md': ['0.875rem', { lineHeight: '1.5' }],
        'label-sm': ['0.6875rem', { lineHeight: '1.2', letterSpacing: '0.16em', fontWeight: '700' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
      boxShadow: {
        ambient: '0 0 28px rgba(195, 245, 255, 0.12)',
        'ambient-error': '0 0 28px rgba(255, 180, 171, 0.18)',
      },
      backdropBlur: {
        panel: '16px',
      },
      backgroundImage: {
        'flood-gradient': 'linear-gradient(105deg, rgba(195,245,255,0.95) 0%, rgba(0,229,255,0.98) 100%)',
      },
    },
  },
  plugins: [],
};
